In [2]:
import pandas as pd
import numpy as np

# Series

In [3]:
# 生成一个Series
ser_obj = pd.Series(range(10, 20))
print(ser_obj)
print('\n')
# 获取数据
print(ser_obj.values)
print('\n')
# 获取索引
print(ser_obj.index)
print('\n')
print(ser_obj.dtype)

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64


[10 11 12 13 14 15 16 17 18 19]


RangeIndex(start=0, stop=10, step=1)


int64


In [4]:
print(ser_obj[0])
# 访问不存在的索引下标会报错
# ser_obj[10]

10


In [11]:
print(ser_obj * 2)
print('\n')
print(ser_obj > 15)

0    20
1    22
2    24
3    26
4    28
5    30
6    32
7    34
8    36
9    38
dtype: int64


0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
dtype: bool


In [15]:
# 字典变为Series
year_data = {2001: 17.8, 2005: 20.1, 2003: 16.5}
ser_obj2 = pd.Series(year_data)
print(ser_obj2)
print('\n')
print(ser_obj2.index)
print('\n')
print(ser_obj2[2001])
print('\n')
print(ser_obj2.values)

2001    17.8
2005    20.1
2003    16.5
dtype: float64


Int64Index([2001, 2005, 2003], dtype='int64')


17.8


[17.8 20.1 16.5]


In [18]:
print(ser_obj2.name)
print('\n')
# 索引名字
print(ser_obj2.index.name)
print('\n')
ser_obj2.name = 'temp'
ser_obj2.index.name = 'year'
# head默认显示前五行
print(ser_obj2.head())

None


None


year
2001    17.8
2005    20.1
2003    16.5
Name: temp, dtype: float64


# DateFrame

In [23]:
# 通过ndarray构建DataFrame
t = pd.DataFrame(np.arange(12).reshape(3, 4))
print(t)
print('\n')
array = np.random.randn(5, 4)
print(array)
print('\n')
df_obj = pd.DataFrame(array)
print(df_obj.head())

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11


[[ 0.58894419 -0.17657309 -1.28600369  1.43933435]
 [-0.61272708  0.78787435  0.59362461 -0.36371562]
 [-0.41766242 -1.38974571  0.2556957   0.00686137]
 [-0.83998946  0.19907914  0.51141692  1.0933934 ]
 [ 0.26699557  0.58833277  0.46936258  2.02506929]]


          0         1         2         3
0  0.588944 -0.176573 -1.286004  1.439334
1 -0.612727  0.787874  0.593625 -0.363716
2 -0.417662 -1.389746  0.255696  0.006861
3 -0.839989  0.199079  0.511417  1.093393
4  0.266996  0.588333  0.469363  2.025069


In [26]:
# 字典变df
d2 = [{"name": "xiaohong", "age": 32, "tel": 10010},
      {"name": "xiaogang", "tel": 10000},
      {"name": "xiaowang", "age": 22}]
df1 = pd.DataFrame(d2)
print(df1)
print('\n')
print(df1.values)
print('\n')
print(type(df1.values))

       name   age      tel
0  xiaohong  32.0  10010.0
1  xiaogang   NaN  10000.0
2  xiaowang  22.0      NaN


[['xiaohong' 32.0 10010.0]
 ['xiaogang' nan 10000.0]
 ['xiaowang' 22.0 nan]]


<class 'numpy.ndarray'>


In [32]:
# df中不同列可以是不同的数据类型,同一列必须是一个数据类型
dict_data = {'A': 1,
             'B': pd.Timestamp('20190926'),
             'C': pd.Series(1, index=list(range(4)), dtype='float32'),
             'D': np.array([1, 2, 3, 4], dtype='int32'),
             'E': ["Python", "Java", "C++", "C"],
             'F': 'yf'}
df_obj2 = pd.DataFrame(dict_data)
print(df_obj2)
print('\n')
print(df_obj2.index)
print('\n')
# df_obj2.index[0] = 2  # 不可以单独修改某个索引值
print(df_obj2.columns)
print('\n')
print(df_obj2.dtypes)  # object

   A          B    C  D       E   F
0  1 2019-09-26  1.0  1  Python  yf
1  1 2019-09-26  1.0  2    Java  yf
2  1 2019-09-26  1.0  3     C++  yf
3  1 2019-09-26  1.0  4       C  yf


Int64Index([0, 1, 2, 3], dtype='int64')


Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')


A             int64
B    datetime64[ns]
C           float32
D             int32
E            object
F            object
dtype: object


In [37]:
dates = pd.date_range('20130101', periods=6)
print(dates)
print('\n')
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('abcd'))
print(df)
print('\n')
print(df.index)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')


                   a         b         c         d
2013-01-01  0.468627  0.022902  0.705456  0.282462
2013-01-02 -1.257396 -1.812142  0.724779 -1.201440
2013-01-03  0.919908  0.614420  0.516280 -0.396140
2013-01-04  1.014616 -0.524819 -1.298802 -0.947715
2013-01-05  1.065585 -0.293346 -1.106446  0.520221
2013-01-06 -1.475758 -0.403859  0.523553 -1.458758


DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')


In [44]:
print(df_obj2)
print('\n')
# 使用索引名来取某一行或者列
print(df_obj2['A'])
print('\n')
# 取出来的一列是Series
print(type(df_obj2['A']))

   A          B    C  D       E   F
0  1 2019-09-26  1.0  1  Python  yf
1  1 2019-09-26  1.0  2    Java  yf
2  1 2019-09-26  1.0  3     C++  yf
3  1 2019-09-26  1.0  4       C  yf


0    1
1    1
2    1
3    1
Name: A, dtype: int64
<class 'pandas.core.series.Series'>


In [45]:
# 增加列数据，列名自定义
df_obj2['G'] = df_obj2['D'] + 4
print(df_obj2['G'])

0    5
1    6
2    7
3    8
Name: G, dtype: int32


In [46]:
# 删除列
del (df_obj2['G'])
print(df_obj2.head())

   A          B    C  D       E   F
0  1 2019-09-26  1.0  1  Python  yf
1  1 2019-09-26  1.0  2    Java  yf
2  1 2019-09-26  1.0  3     C++  yf
3  1 2019-09-26  1.0  4       C  yf


# pandas的索引操作

In [47]:
print(df_obj2.index)

Int64Index([0, 1, 2, 3], dtype='int64')


In [5]:
# 索引对象的值不可变
# df_obj2.index[0] = 2

常见的Index种类
Index，索引
Int64Index，整数索引
MultiIndex，层级索引
DatetimeIndex，时间戳类型

In [50]:
ser_obj = pd.Series(range(5), index=list('abcde'))
print(ser_obj)
print('\n')
print(ser_obj.index)

a    0
b    1
c    2
d    3
e    4
dtype: int64


Index(['a', 'b', 'c', 'd', 'e'], dtype='object')


In [52]:
# 行索引，可以用索引名、索引顺序来取
print(ser_obj['b'])
print('\n')
print(ser_obj[2])

1


2


In [55]:
# 切片索引
print(ser_obj[1:3])  # 索引顺序是开区间
print('\n')
print(ser_obj['b':'d'])  # 索引名是闭区间

b    1
c    2
dtype: int64


b    1
c    2
d    3
dtype: int64


In [57]:
# 不连续索引
print(ser_obj[[0, 2, 4]])
print('\n')
print(ser_obj[['a', 'e']])

a    0
c    2
e    4
dtype: int64


a    0
e    4
dtype: int64


In [60]:
# 布尔索引
ser_bool = ser_obj > 2
print(ser_bool)
print('\n')
print(ser_obj[ser_bool])
print('\n')
print(ser_obj[ser_obj > 2])

a    False
b    False
c    False
d     True
e     True
dtype: bool


d    3
e    4
dtype: int64


d    3
e    4
dtype: int64


# DataFrame索引

In [63]:
df_obj = pd.DataFrame(np.random.randn(5, 4), columns=list('abcd'))
print(df_obj)

          a         b         c         d
0 -2.153364 -0.533871 -0.171321  0.180533
1  1.060474  1.772034 -0.171434 -1.626997
2  0.122230  0.326178 -0.229190  0.731398
3 -2.069778  0.317027  1.263360  1.244685
4  1.106842  0.617018 -0.628593 -0.171215


In [68]:
# 列索引
print(df_obj['a'])  # 返回Series类型
print('\n')
print(df_obj[['a']])  # 返回DataFrame类型
print('\n')
print(type(df_obj[['a']]))

0   -2.153364
1    1.060474
2    0.122230
3   -2.069778
4    1.106842
Name: a, dtype: float64


          a
0 -2.153364
1  1.060474
2  0.122230
3 -2.069778
4  1.106842


<class 'pandas.core.frame.DataFrame'>


loc 标签索引

In [73]:
# 建议使用loc，效率更高

# Series
print(ser_obj)
print('\n')
print(ser_obj['b':'d'])
print('\n')
print(ser_obj.loc['b':'d'])

a    0
b    1
c    2
d    3
e    4
dtype: int64


b    1
c    2
d    3
dtype: int64


b    1
c    2
d    3
dtype: int64


In [79]:
# DataFrame
df_obj = pd.DataFrame(np.random.randn(5, 4), columns=list('dcba'), index=list('abcde'))
print(df_obj)
print('\n')
print(df_obj['a'])  # 不建议用
print('\n')
print(df_obj.loc['a'])  # 拿的是行
print('\n')
# 第一个参数是行，第二个参数是列
print(df_obj.loc['a':'c', 'd':'b'])
print('\n')
print(df_obj.loc[['a', 'c'], 'd':'b'])

          d         c         b         a
a  0.849955 -1.715393 -0.286376  1.680999
b -0.009370  1.346242 -0.924500 -0.542729
c -0.117532  0.264189  0.596576 -0.997622
d -0.966300  1.211790  0.772415 -0.714441
e  0.945344 -1.053741 -0.659653 -0.722030


a    1.680999
b   -0.542729
c   -0.997622
d   -0.714441
e   -0.722030
Name: a, dtype: float64


d    0.849955
c   -1.715393
b   -0.286376
a    1.680999
Name: a, dtype: float64


          d         c         b
a  0.849955 -1.715393 -0.286376
b -0.009370  1.346242 -0.924500
c -0.117532  0.264189  0.596576


          d         c         b
a  0.849955 -1.715393 -0.286376
c -0.117532  0.264189  0.596576


iloc 位置索引

In [82]:
# Series
print(ser_obj[1:3])
print('\n')
print(ser_obj.iloc[1:3])  # 左闭右开

b    1
c    2
dtype: int64


b    1
c    2
dtype: int64


In [86]:
# DataFrame
print(df_obj.iloc[0:2, 0:2])

          d         c
a  0.849955 -1.715393
b -0.009370  1.346242


# 对齐运算

In [6]:
# Series对齐运算
s1 = pd.Series(range(10, 20), index=range(10))
s2 = pd.Series(range(20, 25), index=range(5))
s3 = s1 + s2
print(s3)
print('\n')
print(s3[6])
print('\n')
# 未对齐的数据将和填充值做运算
print(s1.add(s2, fill_value=0))  # 填充值设为0

0    30.0
1    32.0
2    34.0
3    36.0
4    38.0
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
dtype: float64


nan


0    30.0
1    32.0
2    34.0
3    36.0
4    38.0
5    15.0
6    16.0
7    17.0
8    18.0
9    19.0
dtype: float64


In [13]:
# df对齐运算
df1 = pd.DataFrame(np.ones((2, 2)), columns=['a', 'b'])
df2 = pd.DataFrame(np.ones((3, 3)), columns=['a', 'b', 'c'])
print(df2)
print('\n')
print(df1 - df2)
print('\n')
print(df1.sub(df2, fill_value=2))

     a    b    c
0  1.0  1.0  1.0
1  1.0  1.0  1.0
2  1.0  1.0  1.0


     a    b   c
0  0.0  0.0 NaN
1  0.0  0.0 NaN
2  NaN  NaN NaN


     a    b    c
0  0.0  0.0  1.0
1  0.0  0.0  1.0
2  1.0  1.0  1.0


# pandas的函数应用

In [15]:
df = pd.DataFrame(np.random.randn(5, 4) - 1)
print(df)
print('\n')
print(np.abs(df))

          0         1         2         3
0 -1.482975 -1.156931 -2.503368 -0.381045
1 -0.265168 -0.230927  0.272352 -1.551387
2 -1.366373 -0.150038 -0.889095 -1.015682
3 -2.211520 -0.436181 -0.560037 -1.036768
4 -3.753020  0.611333 -1.170228 -1.521418


          0         1         2         3
0  1.482975  1.156931  2.503368  0.381045
1  0.265168  0.230927  0.272352  1.551387
2  1.366373  0.150038  0.889095  1.015682
3  2.211520  0.436181  0.560037  1.036768
4  3.753020  0.611333  1.170228  1.521418


In [17]:
# apply，默认作用在列上
print(df.apply(lambda x: x.max()))
# 作用在行上
print(df.apply(lambda x: x.max(), axis=1))

0   -0.265168
1    0.611333
2    0.272352
3   -0.381045
dtype: float64
0   -0.381045
1    0.272352
2   -0.150038
3   -0.436181
4    0.611333
dtype: float64


In [18]:
type('%.2f' % 1.3456)

str

# 索引排序

In [28]:
# Series
print(np.random.randint(5, size=5))
print('\n')
s4 = pd.Series(range(10, 15), index=np.random.randint(5, size=5))
print(s4)
print('\n')
# 索引排序,sort_index返回一个新的排好索引的series
print(s4.sort_index())
print('\n')
print(s4)
print('\n')
# print(s4.loc[0:3])  # loc索引不唯一时会报错
print(s4.iloc[0:3])
print('\n')
print(s4[0:3])  # 默认用的位置索引

[3 0 2 0 0]


0    10
0    11
1    12
1    13
3    14
dtype: int64


0    10
0    11
1    12
1    13
3    14
dtype: int64


0    10
0    11
1    12
1    13
3    14
dtype: int64


0    10
0    11
1    12
dtype: int64


0    10
0    11
1    12
dtype: int64


In [39]:
# DataFrame
df4 = pd.DataFrame(np.random.randn(5, 5),
                   index=np.random.randint(5, size=5),
                   columns=np.random.randint(5, size=5))
print(df4)
print('\n')
# 轴0是行索引序列，ascending默认为True，升序
df4_isort = df4.sort_index(axis=0)
print(df4_isort)
print('\n')
# 轴1是列索引序列，ascending默认为True，升序
df4_isort = df4.sort_index(axis=1, ascending=False)
print(df4_isort)

          2         1         3         0         3
0  0.949652 -0.720869 -0.222386 -0.028994 -1.391245
3  0.239206  0.855429 -1.487326 -1.394358  1.511589
4  0.628212  0.534477 -0.202843 -0.450802  0.269830
3  2.297188  0.500388 -1.104566 -0.457882 -0.841150
3  2.084293 -0.107511  0.062981  0.179535 -1.269046


          2         1         3         0         3
0  0.949652 -0.720869 -0.222386 -0.028994 -1.391245
3  0.239206  0.855429 -1.487326 -1.394358  1.511589
3  2.297188  0.500388 -1.104566 -0.457882 -0.841150
3  2.084293 -0.107511  0.062981  0.179535 -1.269046
4  0.628212  0.534477 -0.202843 -0.450802  0.269830


          3         3         2         1         0
0 -0.222386 -1.391245  0.949652 -0.720869 -0.028994
3 -1.487326  1.511589  0.239206  0.855429 -1.394358
4 -0.202843  0.269830  0.628212  0.534477 -0.450802
3 -1.104566 -0.841150  2.297188  0.500388 -0.457882
3  0.062981 -1.269046  2.084293 -0.107511  0.179535


# 按值排序

In [44]:
# 按值排序,by后是column的值
import random

l = [random.randint(0, 100) for i in range(24)]
df4 = pd.DataFrame(np.array(l).reshape(6, 4))
print(df4.values)
print('\n')
print(df4)
print('\n')
# 按轴零排序，by后是列名
df4_vsort = df4.sort_values(by=3, axis=0, ascending=False)  # 寻找的是columns里的3
print(df4_vsort)
print('\n')
# 按轴1排序，by后是行名
df4_vsort = df4.sort_values(by=3, axis=1, ascending=False)  # 寻找的是index里的3
print(df4_vsort)

[[  5  59  56 100]
 [ 86  95  89  97]
 [ 58  10  33  22]
 [100  34  26   9]
 [ 70  17  94  43]
 [ 67  40  59  61]]


     0   1   2    3
0    5  59  56  100
1   86  95  89   97
2   58  10  33   22
3  100  34  26    9
4   70  17  94   43
5   67  40  59   61


     0   1   2    3
0    5  59  56  100
1   86  95  89   97
5   67  40  59   61
4   70  17  94   43
2   58  10  33   22
3  100  34  26    9


     0   1   2    3
0    5  59  56  100
1   86  95  89   97
2   58  10  33   22
3  100  34  26    9
4   70  17  94   43
5   67  40  59   61


# 处理缺失数据

In [53]:
df_data = pd.DataFrame([np.random.randn(3), [1., 2., np.nan],
                        [np.nan, 4., np.nan], [1., 2., 3.]])
print(df_data.head())

          0         1         2
0  0.611867  0.715574 -0.157597
1  1.000000  2.000000       NaN
2       NaN  4.000000       NaN
3  1.000000  2.000000  3.000000


In [49]:
# isnull来判断是否有空的数据
print(df_data.isnull())

       0      1      2
0  False  False  False
1  False  False   True
2   True  False   True
3  False  False  False


In [50]:
# 默认某一行有空值，删除整行
print(df_data.dropna(inplace=True))
print('\n')
print(df_data)

None


          0         1         2
0 -0.181577 -0.696243  0.855118
3  1.000000  2.000000  3.000000


In [52]:
# 某列有空值，就删除该列，常用于某个特征确实太多时
print(df_data.dropna(axis=1))

          1
0  0.058668
1  2.000000
2  4.000000
3  2.000000


In [54]:
# 给零列的空值填为-100，按特征（按列）去填充
print(df_data.iloc[:, 0].fillna(-100.))

0      0.611867
1      1.000000
2   -100.000000
3      1.000000
Name: 0, dtype: float64


In [55]:
# 依次拿每一列
for i in df_data.columns:
    print(df_data.loc[:, i])

0    0.611867
1    1.000000
2         NaN
3    1.000000
Name: 0, dtype: float64
0    0.715574
1    2.000000
2    4.000000
3    2.000000
Name: 1, dtype: float64
0   -0.157597
1         NaN
2         NaN
3    3.000000
Name: 2, dtype: float64


# 层级索引（hierarchical indexing）

In [66]:
# MultiIndex是层级索引，索引类型的一种
index1 = pd.MultiIndex.from_arrays([['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'c', 'd', 'd', 'd'],
                                    [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]], names=['cloth', 'size'])

ser_obj = pd.Series(np.random.randn(12), index=index1)
print(ser_obj)
print('\n')
print(type(ser_obj))
print('\n')
print(type(ser_obj.index))
print('\n')
print(ser_obj.index)
print('\n')
print(ser_obj.index.levels)
print('\n')
print(ser_obj.index.codes)

cloth  size
a      0       0.463495
       1       1.599870
       2       0.048820
b      0       2.105457
       1       1.060499
       2       1.317123
c      0      -0.231728
       1       0.877534
       2       1.615050
d      0      -0.971104
       1       0.045689
       2      -0.781595
dtype: float64


<class 'pandas.core.series.Series'>


<class 'pandas.core.indexes.multi.MultiIndex'>


MultiIndex([('a', 0),
            ('a', 1),
            ('a', 2),
            ('b', 0),
            ('b', 1),
            ('b', 2),
            ('c', 0),
            ('c', 1),
            ('c', 2),
            ('d', 0),
            ('d', 1),
            ('d', 2)],
           names=['cloth', 'size'])


[['a', 'b', 'c', 'd'], [0, 1, 2]]


[[0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3], [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]]


In [58]:
# 层级索引如何取数据
print(ser_obj)
print('\n')
print(ser_obj['c'])
print('\n')
print(ser_obj['a', 2])
print('\n')
print(ser_obj[:, 2])

cloth  size
a      0       0.328510
       1      -0.103232
       2       0.822804
b      0      -1.009461
       1       1.744465
       2      -0.550116
c      0       1.001055
       1       1.758354
       2      -0.260206
d      0      -0.925041
       1       0.818996
       2       1.851973
dtype: float64


size
0    1.001055
1    1.758354
2   -0.260206
dtype: float64


0.8228035992568921


cloth
a    0.822804
b   -0.550116
c   -0.260206
d    1.851973
dtype: float64


In [59]:
# 交换层级
print(ser_obj)
print('\n')
print(ser_obj.swaplevel())
print('\n')
print(ser_obj)
print('\n')
ser_obj = ser_obj.swaplevel()
print(ser_obj)

cloth  size
a      0       0.328510
       1      -0.103232
       2       0.822804
b      0      -1.009461
       1       1.744465
       2      -0.550116
c      0       1.001055
       1       1.758354
       2      -0.260206
d      0      -0.925041
       1       0.818996
       2       1.851973
dtype: float64


size  cloth
0     a        0.328510
1     a       -0.103232
2     a        0.822804
0     b       -1.009461
1     b        1.744465
2     b       -0.550116
0     c        1.001055
1     c        1.758354
2     c       -0.260206
0     d       -0.925041
1     d        0.818996
2     d        1.851973
dtype: float64


cloth  size
a      0       0.328510
       1      -0.103232
       2       0.822804
b      0      -1.009461
       1       1.744465
       2      -0.550116
c      0       1.001055
       1       1.758354
       2      -0.260206
d      0      -0.925041
       1       0.818996
       2       1.851973
dtype: float64


size  cloth
0     a        0.328510
1     a      

In [63]:
print(ser_obj.sort_index(level=1))  # 层级索引按哪个索引级别排序
print('\n')
# 把0索引（最外层索引）变为列索引
df_obj=ser_obj.unstack(0)  # unstack可以放索引名，或者索引位置
print(df_obj)

cloth  size
a      0       0.631216
b      0      -1.946660
c      0      -1.209985
d      0       2.506305
a      1       0.542148
b      1       1.966832
c      1       0.318532
d      1      -1.243302
a      2       1.001339
b      2       0.889609
c      2       0.075547
d      2       2.519767
dtype: float64


cloth         a         b         c         d
size                                         
0      0.631216 -1.946660 -1.209985  2.506305
1      0.542148  1.966832  0.318532 -1.243302
2      1.001339  0.889609  0.075547  2.519767


In [69]:
print(df_obj)
print('\n')
# 对df进行stack，就会把行、列索引进行堆叠，变为Series
# 把列索引放入内层,只能放到内层
print(df_obj.stack())  # stack变为sSeries和unstack保持一致的
print('\n')
df_obj=df_obj.transpose()
print(df_obj)

size          0         1         2
cloth                              
a      0.631216  0.542148  1.001339
b     -1.946660  1.966832  0.889609
c     -1.209985  0.318532  0.075547
d      2.506305 -1.243302  2.519767


cloth  size
a      0       0.631216
       1       0.542148
       2       1.001339
b      0      -1.946660
       1       1.966832
       2       0.889609
c      0      -1.209985
       1       0.318532
       2       0.075547
d      0       2.506305
       1      -1.243302
       2       2.519767
dtype: float64


cloth         a         b         c         d
size                                         
0      0.631216 -1.946660 -1.209985  2.506305
1      0.542148  1.966832  0.318532 -1.243302
2      1.001339  0.889609  0.075547  2.519767
