In [1]:
from sklearn.datasets import load_iris, fetch_20newsgroups, load_boston
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report
from sklearn.feature_extraction import DictVectorizer
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np
from sklearn.metrics import roc_auc_score

In [10]:
# 鸢尾花数据集，查看特征，目标，样本量
li = load_iris()

print(li.data.shape)
print('\n')
print(type(li.data))
print('\n')
print('目标值')
print(li.target)
print('\n')
print('描述')
print(li.DESCR)
print('特征名')
print(li.feature_names)
print('\n')
print('目标名')
print(li.target_names)

(150, 4)


<class 'numpy.ndarray'>


目标值
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


描述
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlat

In [16]:
# random_state 随机数种子,不同的种子会造成不同的随机采样结果,相同的种子采样结果相同
x_train, x_test, y_train, y_test = train_test_split(li.data, li.target, test_size=0.25, random_state=1)
print("训练集特征值和目标值：", x_train, y_train)
print("训练集特征值shape", x_train.shape)
print('\n')
print("测试集特征值和目标值：", x_test, y_test)
print("测试集特征值shape", x_test.shape)

训练集特征值和目标值： [[6.5 2.8 4.6 1.5]
 [6.7 2.5 5.8 1.8]
 [6.8 3.  5.5 2.1]
 [5.1 3.5 1.4 0.3]
 [6.  2.2 5.  1.5]
 [6.3 2.9 5.6 1.8]
 [6.6 2.9 4.6 1.3]
 [7.7 2.6 6.9 2.3]
 [5.7 3.8 1.7 0.3]
 [5.  3.6 1.4 0.2]
 [4.8 3.  1.4 0.3]
 [5.2 2.7 3.9 1.4]
 [5.1 3.4 1.5 0.2]
 [5.5 3.5 1.3 0.2]
 [7.7 3.8 6.7 2.2]
 [6.9 3.1 5.4 2.1]
 [7.3 2.9 6.3 1.8]
 [6.4 2.8 5.6 2.2]
 [6.2 2.8 4.8 1.8]
 [6.  3.4 4.5 1.6]
 [7.7 2.8 6.7 2. ]
 [5.7 3.  4.2 1.2]
 [4.8 3.4 1.6 0.2]
 [5.7 2.5 5.  2. ]
 [6.3 2.7 4.9 1.8]
 [4.8 3.  1.4 0.1]
 [4.7 3.2 1.3 0.2]
 [6.5 3.  5.8 2.2]
 [4.6 3.4 1.4 0.3]
 [6.1 3.  4.9 1.8]
 [6.5 3.2 5.1 2. ]
 [6.7 3.1 4.4 1.4]
 [5.7 2.8 4.5 1.3]
 [6.7 3.3 5.7 2.5]
 [6.  3.  4.8 1.8]
 [5.1 3.8 1.6 0.2]
 [6.  2.2 4.  1. ]
 [6.4 2.9 4.3 1.3]
 [6.5 3.  5.5 1.8]
 [5.  2.3 3.3 1. ]
 [6.3 3.3 6.  2.5]
 [5.5 2.5 4.  1.3]
 [5.4 3.7 1.5 0.2]
 [4.9 3.1 1.5 0.2]
 [5.2 4.1 1.5 0.1]
 [6.7 3.3 5.7 2.1]
 [4.4 3.  1.3 0.2]
 [6.  2.7 5.1 1.6]
 [6.4 2.7 5.3 1.9]
 [5.9 3.  5.1 1.8]
 [5.2 3.5 1.5 0.2]
 [5.1 3.3 1.7 0.5]


In [29]:
# subset代表下载的数据集类型，默认是train，只有训练集
news = fetch_20newsgroups(subset='all', data_home='data')
print(type(news.data))
print('\n')
print(len(news.data))
print('\n')
print(news.DESCR)
print('\n')
print(news.data[0])
print('\n')
print(news.target[0])
print('\n')
print(news.target)
print('\n')
print(min(news.target), max(news.target))

<class 'list'>


18846


From: Mamatha Devineni Ratnam <mr47+@andrew.cmu.edu>
Subject: Pens fans reactions
Organization: Post Office, Carnegie Mellon, Pittsburgh, PA
Lines: 12
NNTP-Posting-Host: po4.andrew.cmu.edu



I am sure some bashers of Pens fans are pretty confused about the lack
of any kind of posts about the recent Pens massacre of the Devils. Actually,
I am  bit puzzled too and a bit relieved. However, I am going to put an end
to non-PIttsburghers' relief with a bit of praise for the Pens. Man, they
are killing those Devils worse than I thought. Jagr just showed you why
he is much better than his regular season stats. He is also a lot
fo fun to watch in the playoffs. Bowman should let JAgr have a lot of
fun in the next couple of games since the Pens are going to beat the pulp out of Jersey anyway. I was very disappointed not to see the Islanders lose the final
regular season game.          PENS RULE!!!




10


[10  3 17 ...  3  1  7]


0 19


In [38]:
lb = load_boston()
print(type(lb.data))
print('\n')
print(lb.data.shape)
print('\n')
print(lb.data[0])
print('\n')
print(lb.target[0])
print('\n')
print(lb.DESCR)
print('\n')
print(lb.feature_names)
# 回归问题没这个
# print(lb.target_names)

<class 'numpy.ndarray'>


(506, 13)


[6.320e-03 1.800e+01 2.310e+00 0.000e+00 5.380e-01 6.575e+00 6.520e+01
 4.090e+00 1.000e+00 2.960e+02 1.530e+01 3.969e+02 4.980e+00]


24.0


.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distan

d:\软件\python39\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.
    :f

# 分类算法

## K近邻

In [ ]:
# K近邻预测用户签到位置

# 读取数据
data = pd.read_csv('./data/FBlocation/train.csv')
print(data.head(10))
print('\n')
print(data.shape)
print('\n')
# 处理数据
# 缩小数据，减少计算时间
data = data.query('x > 1.0 & x < 1.25 & y > 2.5 & y < 2.75')
# 处理时间的数据
time_value = pd.to_datetime(data['time'], unit='s')  # 秒
print(time_value)
print('\n')

# 把日期、时间格式转换为字典格式
time_value = pd.DatetimeIndex(time_value)
print(time_value)

# 构造一些特征
data['day'] = time_value.day
data['hour'] = time_value.hour
data['weekday'] = time_value.weekday
# 把time特征删除
data = data.drop(['time'], axis=1)
print(data)
print('\n')

# 每个地点去的人数
place_count = data.groupby('place_id').count()
print(place_count)
print('\n')
# 只选择去的人大于3的数据，认为1,2,3的是噪音，这个地方去的人很少
tf = place_count[place_count.row_id > 3].reset_index()
print(tf)

# 根据设定的地点目标值，对原本的样本进行过滤
data = data[data['place_id'].isin(tf.place_id)]
print(data)

# 取出处理后的数据当中的特征值和目标值
# y是目标值
y = data['place_id']
# print(y)
# 删除目标值，保留特征值
x = data.drop(['place_id'], axis=1)
# 删除无用的特征值,认为row_id是无用的
x = x.drop(['row_id'], axis=1)
print(x.shape)
print('\n')
print(x.columns)

# 进行数据的分割，训练集合测试集
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=1)
# 特征工程（标准化）
std = StandardScaler()
# 对测试集和训练集的特征值进行标准化，训练集用fit_transform
x_train = std.fit_transform(x_train)
print(std.mean_)
print(std.var_)
print('\n')
# 测试集用transform，transform不再进行均值和方差的计算
x_test = std.transform(x_test)
print(std.mean_)
print(std.var_)

# 进行算法流程
# 超参数，可以通过设置n_neighbors，来调整结果好坏
# 网格搜索和交叉验证
knn = KNeighborsClassifier()
param = {'n_neighbors': [1, 3, 5, 8, 10]}
gc = GridSearchCV(knn, param_grid=param,cv=3)
gc.fit(x_train, y_train)
y_predict = gc.predict(x_test)
print('预测的目标签到位置为：', y_predict)
print('预测的准确率：', gc.score(x_test, y_test))
print("在交叉验证当中最好的结果：", gc.best_score_)
print("选择最好的模型是：", gc.best_estimator_)
print("每个超参数每次交叉验证的结果：", gc.cv_results_)

## 朴素贝叶斯

In [6]:
news = fetch_20newsgroups(subset='all', data_home='data')
print(len(news.data))
print(news.target)
print(news.target_names)
print('\n')

# 数据分割
# 训练集的特征值x_train 测试集的特征值x_test 训练集的目标值y_train 测试集的目标值y_test
x_train, x_test, y_train, y_test = train_test_split(news.data, news.target, test_size=0.25, random_state=1)

# 特征工程
tf = TfidfVectorizer()
x_train = tf.fit_transform(x_train)
x_test = tf.transform(x_test)

# 机器学习（模型训练）
# 朴素贝叶斯算法,alpha是拉普拉斯平滑系数
mlt = MultinomialNB(alpha=1.0)
mlt.fit(x_train, y_train)

# 模型评估
y_predict = mlt.predict(x_test)
print('预测的文章类别为：', y_predict)
print('\n')
print('准确率为：', mlt.score(x_test, y_test))
print('\n')
print('每个类别的精确率和召回率：', classification_report(y_test, y_predict, target_names=news.target_names))

18846
[10  3 17 ...  3  1  7]
['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']


预测的文章类别为： [16 19 18 ... 13  7 14]


准确率为： 0.8518675721561969


每个类别的精确率和召回率：                           precision    recall  f1-score   support

             alt.atheism       0.91      0.77      0.83       199
           comp.graphics       0.83      0.79      0.81       242
 comp.os.ms-windows.misc       0.89      0.83      0.86       263
comp.sys.ibm.pc.hardware       0.80      0.83      0.81       262
   comp.sys.mac.hardware       0.90      0.88      0.89       234
          comp.windows.x       0.92      0.85      0.88       230
            misc.forsale       0.9

### AUC

In [9]:
# 把0-20总计20个分类变为0和1
y_test1 = np.where(y_test == 5, 1, 0)
print(y_test1.sum())  # 测试集的目标值中为第5类的数量
y_predict1 = np.where(y_predict == 5, 1, 0)
print(y_predict1.sum())  # 预测的为第五类的数量
# roc_auc_score的y_test只能是二分类
print('AUC指标：', roc_auc_score(y_test1, y_predict1))

230
214
AUC指标： 0.924078924393225
