In [1]:
import matplotlib as mpl
% matplotlib inline
import numpy as np
import sklearn
import pandas as pd
import os
import sys
import time
import tensorflow as tf

from tensorflow import keras

print(tf.__version__)
print(sys.version_info)
for module in mpl, np, pd, sklearn, tf, keras:
    print(module.__name__, module.__version__)

2.9.1
sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)
matplotlib 3.5.2
numpy 1.23.0
pandas 1.4.3
sklearn 1.1.1
tensorflow 2.9.1
keras.api._v2.keras 2.9.0


In [11]:
# constant是常量张量
t = tf.constant([[1., 2., 3.], [4., 5., 6.]])
print(t)
print('-' * 50)
print(type(t))

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
--------------------------------------------------
<class 'tensorflow.python.framework.ops.EagerTensor'>
--------------------------------------------------


In [13]:
# index
print(t[:, 1:])
print('-' * 50)
print(t[..., 1])
print('-' * 50)
print(type(t[..., 1]))  # 等价t[:,1]
print('-' * 50)
# print(t[:,1])
# print('-'*50)
# print(type(t[:,1]))
# print('-'*50)
# t.assign(1)对常量不能进行再次assign设置
print(type(t.numpy()))
print('-' * 50)
q = t.numpy()
print(q)

tf.Tensor(
[[2. 3.]
 [5. 6.]], shape=(2, 2), dtype=float32)
--------------------------------------------------
tf.Tensor([2. 5.], shape=(2,), dtype=float32)
--------------------------------------------------
<class 'tensorflow.python.framework.ops.EagerTensor'>
--------------------------------------------------
<class 'numpy.ndarray'>
--------------------------------------------------
[[1. 2. 3.]
 [4. 5. 6.]]


In [14]:
t1 = tf.constant(q)  # 把ndarray变为张量
print(t1)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


In [16]:
# ops 使用tf本身的math接口对Tensor进行计算
print(t + 10)
print('-' * 50)
print(t)  # t本身并未改变
print('-' * 50)
print(tf.square(t))  # 平方
print('-' * 50)
print(t)  # t本身并未改变
print('-' * 50)
print(tf.transpose(t))  # 转置
print('-' * 50)
print(t @ tf.transpose(t))  # @是矩阵乘法，和*不一样
print('-' * 50)
print(t * t)  # 对应位置相乘

tf.Tensor(
[[11. 12. 13.]
 [14. 15. 16.]], shape=(2, 3), dtype=float32)
--------------------------------------------------
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
--------------------------------------------------
tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float32)
--------------------------------------------------
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
--------------------------------------------------
tf.Tensor(
[[1. 4.]
 [2. 5.]
 [3. 6.]], shape=(3, 2), dtype=float32)
--------------------------------------------------
tf.Tensor(
[[14. 32.]
 [32. 77.]], shape=(2, 2), dtype=float32)
--------------------------------------------------
tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float32)


In [17]:
print(tf.sqrt(t))  # 开方
print('-' * 50)
print(tf.math.sqrt(t))  # 开方
print('-' * 50)
print(tf.math.log(t))  # 必须加math

tf.Tensor(
[[1.        1.4142135 1.7320508]
 [2.        2.2360678 2.4494896]], shape=(2, 3), dtype=float32)
--------------------------------------------------
tf.Tensor(
[[1.        1.4142135 1.7320508]
 [2.        2.2360678 2.4494896]], shape=(2, 3), dtype=float32)
--------------------------------------------------


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.       , 0.6931472, 1.0986123],
       [1.3862944, 1.609438 , 1.7917595]], dtype=float32)>

In [18]:
# numpy conversion
print(t.numpy())  # 可以直接通过numpy取出来
print('-' * 50)
print(t.numpy().tolist())
print('-' * 50)
print(type(t.numpy()))
print('-' * 50)
print(np.square(t))  # 也可以用np.square求平方
print('-' * 50)
np_t = np.array([[1., 2., 3.], [4., 5., 6.]])
print(tf.constant(np_t))  # 转换为tensor（张量）

[[1. 2. 3.]
 [4. 5. 6.]]
--------------------------------------------------
[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]
--------------------------------------------------
<class 'numpy.ndarray'>
--------------------------------------------------
[[ 1.  4.  9.]
 [16. 25. 36.]]
--------------------------------------------------
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float64)


In [21]:
# Scalars:就是标量，只有一个数值的张量，称为标量
t = tf.constant(2.718)
print(t)
print('-' * 50)
print(type(t))
print('-' * 50)
print(t.numpy())
print('-' * 50)
print(t.shape)  # 维数

tf.Tensor(2.718, shape=(), dtype=float32)
--------------------------------------------------
<class 'tensorflow.python.framework.ops.EagerTensor'>
--------------------------------------------------
2.718
--------------------------------------------------
()


# 张量字符串常量

In [22]:
# strings
t = tf.constant("cafe")
print(t)
print('-' * 50)
print(tf.strings.length(t))
print('-' * 50)
print(tf.strings.length(t, unit="UTF8_CHAR"))
print('-' * 50)
print(tf.strings.unicode_decode(t, "UTF8"))  # 把每一个字符变为ASCII

tf.Tensor(b'cafe', shape=(), dtype=string)
--------------------------------------------------
tf.Tensor(4, shape=(), dtype=int32)
--------------------------------------------------
tf.Tensor(4, shape=(), dtype=int32)
--------------------------------------------------
tf.Tensor([ 99  97 102 101], shape=(4,), dtype=int32)


In [23]:
# string array
t = tf.constant(["cafe", "coffee", "咖啡"])
# 自动求出数组中每一个字符的长度,如果不加unit="UTF8_CHAR"，得到的是实际字节存储的长度
print(tf.strings.length(t, unit="UTF8_CHAR"))
print('-' * 50)
print(tf.strings.length(t, unit="BYTE"))
print('-' * 50)
r = tf.strings.unicode_decode(t, "UTF8")  # 汉字转的是unicode编码
print(r)

tf.Tensor([4 6 2], shape=(3,), dtype=int32)
--------------------------------------------------
tf.Tensor([4 6 6], shape=(3,), dtype=int32)
--------------------------------------------------
<tf.RaggedTensor [[99, 97, 102, 101], [99, 111, 102, 102, 101, 101], [21654, 21857]]>


# RaggedTensor

RaggedTensor是指形状分布不固定的（行元素个数不相等）

In [25]:
# ragged tensor ,每行的元素个数不相等，ndarray是不可以这样的
r = tf.ragged.constant([[11, 12], [21, 22, 23], [], [41]])
print(r)
print('-' * 50)
print(r.shape)
print('-' * 50)

<tf.RaggedTensor [[11, 12], [21, 22, 23], [], [41]]>
--------------------------------------------------
(4, None)
--------------------------------------------------


In [26]:
# index
print(r[1])  # 取一行是Tensor
print('-' * 50)
# 取多行也是ragged tensor
print(r[1:3])
# print(r[:,1])  # 不能取列索引

tf.Tensor([21 22 23], shape=(3,), dtype=int32)
--------------------------------------------------
<tf.RaggedTensor [[21, 22, 23], []]>


In [31]:
# ops on ragged tensor
r2 = tf.ragged.constant([[51, 52], [], [], [71]])
print(tf.concat([r, r2], axis=0))
print('-' * 50)
print(tf.concat([r, r2], axis=1))  # 按轴1进行合并时，行数要一致，行数相等，可以拼
print('-'*50)
# r3 = tf.ragged.constant([[13, 14], [15], [42, 43]])  # 如果行数不相等，不可以拼
# print(tf.concat([r, r3], axis=1))

<tf.RaggedTensor [[11, 12], [21, 22, 23], [], [41], [51, 52], [], [], [71]]>
--------------------------------------------------
<tf.RaggedTensor [[11, 12, 51, 52], [21, 22, 23], [], [41, 71]]>
--------------------------------------------------


In [32]:
# 各种深度学习模型必须输入一个tensor,不可以是ragged tensor
print(r.to_tensor())  # 空的补0，只能往后面补

tf.Tensor(
[[11 12  0]
 [21 22 23]
 [ 0  0  0]
 [41  0  0]], shape=(4, 3), dtype=int32)


# SparseTensor

In [33]:
# sparse tensor 可以往前面补零,sparse tensor从第一行依次往下填位置
# sparse tensor 可以存储节省内存空间，磁盘空间
s = tf.SparseTensor(indices=[[0, 1], [1, 0], [2, 3], [3, 2]],  # 位置
                    values=[1., 2., 3., 5],  # 值
                    dense_shape=[4, 4])  # 维数
print(s)
print('-' * 50)
tt = tf.sparse.to_dense(s)
print(tt)

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]
 [3 2]], shape=(4, 2), dtype=int64), values=tf.Tensor([1. 2. 3. 5.], shape=(4,), dtype=float32), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))
--------------------------------------------------
tf.Tensor(
[[0. 1. 0. 0.]
 [2. 0. 0. 0.]
 [0. 0. 0. 3.]
 [0. 0. 5. 0.]], shape=(4, 4), dtype=float32)


In [36]:
# ops on sparse tensors

s2 = s * 2.0
print(s2)
print('-' * 50)
# 不支持加法
try:
    s3 = s + 1
except TypeError as ex:
    print(ex)
print('-' * 50)
s4 = tf.constant([[10., 20.],
                  [30., 40.],
                  [50., 60.],
                  [70., 80.]])
# print(tf.sparse.to_dense(s) @ s4)
print(tf.sparse.sparse_dense_matmul(s, s4))  # 稀疏Tensor和Tensor相乘，和上一句等价

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]
 [3 2]], shape=(4, 2), dtype=int64), values=tf.Tensor([ 2.  4.  6. 10.], shape=(4,), dtype=float32), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))
--------------------------------------------------
unsupported operand type(s) for +: 'SparseTensor' and 'int'
--------------------------------------------------
tf.Tensor(
[[ 30.  40.]
 [ 20.  40.]
 [210. 240.]
 [250. 300.]], shape=(4, 2), dtype=float32)


In [38]:
# sparse tensor
s5 = tf.SparseTensor(indices=[[0, 2], [2, 3], [0, 1]],
                     values=[1., 2., 3.],
                     dense_shape=[3, 4])
# print(tf.sparse.to_dense(s5))  # sparse无顺序时，不能转为tensor，会报错
# print('-' * 50)
print(s5)
print('-' * 50)
s6 = tf.sparse.reorder(s5)  # 没有顺序的sparse tensor必须进行reorder以后才能to_dense
print(s6)
print('-' * 50)
print(tf.sparse.to_dense(s6))

SparseTensor(indices=tf.Tensor(
[[0 2]
 [2 3]
 [0 1]], shape=(3, 2), dtype=int64), values=tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
--------------------------------------------------
SparseTensor(indices=tf.Tensor(
[[0 1]
 [0 2]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([3. 1. 2.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
--------------------------------------------------
tf.Tensor(
[[0. 3. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 2.]], shape=(3, 4), dtype=float32)


# tf.Variable

In [42]:
# Variables 变量
v = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
print(v)
print('-' * 50)
print(type(v))
print('-' * 50)
print(v.value())
print('-' * 50)
print(v.numpy())

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>
--------------------------------------------------
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
--------------------------------------------------
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
--------------------------------------------------
[[1. 2. 3.]
 [4. 5. 6.]]


In [43]:
# 修改变量时要用assign，改变tensor内某个值，空间并没有发生变化，效率高
# assign value
print(id(v))
print('-' * 50)
v.assign(2 * v)  # assign就是赋值，变量就需要通过这个方式赋值
print(id(v))
print('-' * 50)
print(v.numpy())
print('-' * 50)
v[0, 1].assign(42)  # 取某个元素修改
print(v.numpy())
print('-' * 50)
v[1].assign([7., 8., 9.])  # 取某一行修改
print(v.numpy())
print('-' * 50)
print(id(v))

1682250152160
--------------------------------------------------
1682250152160
--------------------------------------------------
[[ 2.  4.  6.]
 [ 8. 10. 12.]]
--------------------------------------------------
[[ 2. 42.  6.]
 [ 8. 10. 12.]]
--------------------------------------------------
[[ 2. 42.  6.]
 [ 7.  8.  9.]]
--------------------------------------------------
1682250152160


In [44]:
try:
    v[1] = [7., 8., 9.]
except TypeError as ex:
    print(ex)

'ResourceVariable' object does not support item assignment


In [45]:
v = 2 * v
print(v)
print('-' * 50)
print(id(v))
print('-' * 50)
print(type(v))  # 用了=后，类型也发生了改变，不再是变量

tf.Tensor(
[[ 4. 84. 12.]
 [14. 16. 18.]], shape=(2, 3), dtype=float32)
--------------------------------------------------
1677179497632
--------------------------------------------------
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [34]:
x = tf.constant([[1., 2], [2., 3.]])
tf.reduce_mean(x, axis=1)  # 平均值

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.5, 2.5], dtype=float32)>