In [1]:
import random
import time
import numpy as np

a = []
for i in range(100000000):
    a.append(random.random())  #random出来的是小数

t1 = time.time()
sum1 = sum(a)
t2 = time.time()

b = np.array(a)  #b是一个ndarray,就是数组
t3 = time.time()
sum2 = np.sum(b)
t4 = time.time()
print(t2 - t1, t4 - t3)

0.38609981536865234 0.11202526092529297


理解ndarray对象


In [2]:
#列表变数组
list1 = [1, 2, 3, 4]
a = np.array(list1)
print(type(a))
print(list1)
print(a)

<class 'numpy.ndarray'>
[1, 2, 3, 4]
[1 2 3 4]


In [4]:
# 传入range生成序列
b = np.array(range(5))
print(b)

[0 1 2 3 4]


In [5]:
# 使用numpy自带的np.arange()生成数组
t3 = np.arange(0, 10, 2)  # 左闭右开
print(t3)

[0 2 4 6 8]


In [6]:
# 调整数组形状
four = np.array([[1, 2, 3], [4, 5, 6]])
# four.shape=(3,2)
# print(four)
four = four.reshape(3, 2)  # reshape返回了一个新的array
print(four)
# 默认情况下‘C’以行为主的顺序展开，‘F’（Fortran风格）意味着以列的顺序展开
five = four.reshape((6,), order='F')  # 6是数组元素个数
print(five)
six = four.flatten()  # 展开成一维
print(six)

[[1 2]
 [3 4]
 [5 6]]
[1 3 5 2 4 6]
[1 2 3 4 5 6]


In [8]:
t = np.arange(24).reshape(4, 6)
print(t.shape)

(4, 6)


In [10]:
#将数组转为list
print(t.tolist())

[[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11], [12, 13, 14, 15, 16, 17], [18, 19, 20, 21, 22, 23]]


numpy的数据类型

In [12]:
f = np.array([1, 2, 3, 4, 5], dtype=np.int16)
print(f.itemsize)  # 单个元素占用空间大小
print(f.dtype)  # 内部的数据类型

f1 = f.astype(np.int64)  # 转换类型
print(f1.dtype)

2
int16
int64
